// base_sampler_tb.v
//
// Self-checking testbench for base_sampler.
// Reads vectors.txt — one "<u_hex(18)> <z0_dec>" pair per line, generated by
// gen_vectors.py from the Python reference — drives u, checks z0.
//
// Build/run: see the Makefile in this directory ("make test").
//
`timescale 1ns/1ps
module base_sampler_tb;

    reg  [71:0] u;
    wire [4:0]  z0;

    base_sampler dut (.u(u), .z0(z0));

    integer fd, r, total, errors;
    reg [71:0] u_in;
    integer    z_exp;

    initial begin
        total  = 0;
        errors = 0;

        fd = $fopen("vectors.txt", "r");
        if (fd == 0) begin
            $display("ERROR: cannot open vectors.txt (run gen_vectors.py first)");
            $finish;
        end

        while (!$feof(fd)) begin
            r = $fscanf(fd, "%h %d\n", u_in, z_exp);
            if (r == 2) begin
                u = u_in;
                #1;                       // let the combinational cone settle
                total = total + 1;
                if (z0 !== z_exp[4:0]) begin
                    errors = errors + 1;
                    if (errors <= 10)
                        $display("MISMATCH  u=%018h  got z0=%0d  exp=%0d",
                                 u_in, z0, z_exp);
                end
            end
        end
        $fclose(fd);

        $display("------------------------------------------------------");
        $display("BaseSampler TB: %0d vectors checked, %0d errors", total, errors);
        if (errors == 0) $display("RESULT: PASS");
        else             $display("RESULT: FAIL");
        $display("------------------------------------------------------");
        $finish;
    end

endmodule
