// keccak_shake256_wrapper_tb.sv
//
// Self-checking testbench for keccak_shake256_wrapper (byte-stream SHAKE256 adapter
// around cshake-core's keccak_top). Reads shake_vectors.txt (generated by
// gen_shake_vectors.py from hashlib.shake_256), drives the absorb/squeeze byte
// interface, and checks every output byte against the Python oracle.
//
// Build/run: see the Makefile in this directory ("make test_shake").

`timescale 1ns/1ps
module keccak_shake256_wrapper_tb;

    reg clk = 0;
    always #5 clk = ~clk;

    reg         rst_n;
    reg         init;
    reg  [31:0] msg_len_bytes, out_len_bytes;
    reg         absorb_valid;
    reg  [7:0]  absorb_data;
    reg         absorb_last;
    wire        ready;
    reg         squeeze_ready;
    wire [7:0]  squeeze_data;
    wire        squeeze_valid;
    wire        busy;

    keccak_shake256_wrapper dut (
        .clk           (clk),
        .rst_n         (rst_n),
        .init          (init),
        .msg_len_bytes (msg_len_bytes),
        .out_len_bytes (out_len_bytes),
        .absorb_valid  (absorb_valid),
        .absorb_data   (absorb_data),
        .absorb_last   (absorb_last),
        .ready         (ready),
        .squeeze_ready (squeeze_ready),
        .squeeze_data  (squeeze_data),
        .squeeze_valid (squeeze_valid),
        .busy          (busy)
    );

    // ── watchdog ──────────────────────────────────────────────────────────────
    initial begin
        #20_000_000;
        $display("TIMEOUT: simulation did not finish in time");
        $finish;
    end

    // ── vector file + driving ────────────────────────────────────────────────
    integer fd;
    integer num_vectors, v, i, r;
    integer mlen, olen;
    integer total_checked, total_errors, byte_errors;
    reg [7:0] msg_buf [0:1023];
    reg [7:0] exp_buf [0:1023];
    integer   tmp;

    initial begin
        rst_n         = 0;
        init          = 0;
        absorb_valid  = 0;
        absorb_data   = 0;
        absorb_last   = 0;
        squeeze_ready = 0;
        total_checked = 0;
        total_errors  = 0;

        fd = $fopen("C:/Users/80010113/Desktop/project/phd_code/my_falcon_build/rtl/shake_vectors.txt", "r");
        if (fd == 0) begin
            $display("ERROR: cannot open shake_vectors.txt (run gen_shake_vectors.py first)");
            $finish;
        end
        r = $fscanf(fd, "%d\n", num_vectors);

        repeat (3) @(posedge clk);
        rst_n = 1;
        repeat (3) @(posedge clk);
        #1;

        for (v = 0; v < num_vectors; v = v + 1) begin
            r = $fscanf(fd, "%d %d\n", mlen, olen);
            for (i = 0; i < mlen; i = i + 1) begin
                r = $fscanf(fd, "%h", tmp);
                msg_buf[i] = tmp[7:0];
            end
            for (i = 0; i < olen; i = i + 1) begin
                r = $fscanf(fd, "%h", tmp);
                exp_buf[i] = tmp[7:0];
            end

            // ── start hash ──
            msg_len_bytes = mlen;
            out_len_bytes = olen;
            init = 1;
            @(posedge clk); #1;
            init = 0;

            // ── absorb ──
            i = 0;
            while (i < mlen) begin
                absorb_data  = msg_buf[i];
                absorb_valid = 1;
                absorb_last  = (i == mlen - 1);
                if (ready) i = i + 1;
                @(posedge clk); #1;
            end
            absorb_valid = 0;
            absorb_last  = 0;

            // ── squeeze ──
            byte_errors   = 0;
            i             = 0;
            squeeze_ready = 1;
            while (i < olen) begin
                if (squeeze_valid) begin
                    if (squeeze_data !== exp_buf[i]) begin
                        byte_errors = byte_errors + 1;
                        if (byte_errors <= 5)
                            $display("  vector %0d (mlen=%0d olen=%0d) byte %0d: got %02h exp %02h",
                                      v, mlen, olen, i, squeeze_data, exp_buf[i]);
                    end
                    i = i + 1;
                end
                @(posedge clk); #1;
            end
            squeeze_ready = 0;

            total_checked = total_checked + 1;
            if (byte_errors > 0) begin
                total_errors = total_errors + 1;
                $display("Vector %0d FAIL (mlen=%0d olen=%0d, %0d byte errors)", v, mlen, olen, byte_errors);
            end

            // wait for DUT to return to idle before starting the next vector
            while (busy) @(posedge clk);
            #1;
        end

        $fclose(fd);
        $display("------------------------------------------------------");
        $display("SHAKE256 wrapper TB: %0d vectors checked, %0d failed", total_checked, total_errors);
        if (total_errors == 0) $display("RESULT: PASS");
        else                   $display("RESULT: FAIL");
        $display("------------------------------------------------------");
        $finish;
    end

endmodule
