// shake256_tb.sv — Self-checking KAT testbench for shake256 + keccak_f1600
//
// Reads shake256_vectors.hex (generated by gen_vectors.py via XKCP Python).
// Format: one byte per line; layout = [num_tests(4B)] then per test:
//         [msg_len(4B)][out_len(4B)][msg bytes][expected bytes]
//
// Run:  make sim          (Vivado XSim, batch)
//       make project      (create .xpr, open in GUI)

`timescale 1ns/1ps

module shake256_tb;

    // ── Clock and reset ───────────────────────────────────────────────────────
    reg clk   = 0;
    reg rst_n = 0;
    always #5 clk = ~clk;   // 100 MHz

    // ── DUT interface ─────────────────────────────────────────────────────────
    reg        init         = 0;
    reg        absorb_valid = 0;
    reg  [7:0] absorb_data  = 0;
    reg        absorb_last  = 0;
    wire       ready;
    reg        squeeze_ready = 0;
    wire [7:0] squeeze_data;
    wire       squeeze_valid;
    wire       busy;

    shake256 dut (
        .clk          (clk),
        .rst_n        (rst_n),
        .init         (init),
        .absorb_valid (absorb_valid),
        .absorb_data  (absorb_data),
        .absorb_last  (absorb_last),
        .ready        (ready),
        .squeeze_ready(squeeze_ready),
        .squeeze_data (squeeze_data),
        .squeeze_valid(squeeze_valid),
        .busy         (busy)
    );

    // ── Test-vector memory (2 KB — enough for all 5 tests) ───────────────────
    reg [7:0] vmem  [0:2047];
    reg [7:0] msg_buf [0:255];
    reg [7:0] exp_buf [0:127];
    reg [7:0] got_buf [0:127];

    // ── Task: absorb a message then wait for busy=0 ───────────────────────────
    task automatic do_absorb;
        input integer len;
        integer k;
        begin
            for (k = 0; k < len; k = k + 1) begin
                while (!ready) @(posedge clk);
                @(negedge clk);
                absorb_valid = 1;
                absorb_data  = msg_buf[k];
                absorb_last  = (k == len - 1);
                @(posedge clk);
            end
            @(negedge clk);
            absorb_valid = 0;
            absorb_last  = 0;
            @(posedge clk);
            // Wait for the final Keccak permutation to complete
            while (busy) @(posedge clk);
        end
    endtask

    // ── Task: squeeze out_len bytes into got_buf ──────────────────────────────
    task automatic do_squeeze;
        input integer out_len;
        integer k;
        begin
            for (k = 0; k < out_len; k = k + 1) begin
                @(negedge clk);
                squeeze_ready = 1;
                @(posedge clk);
                @(negedge clk);
                squeeze_ready = 0;
                // squeeze_valid fires one cycle after squeeze_ready
                @(posedge clk);
                while (!squeeze_valid) @(posedge clk);
                got_buf[k] = squeeze_data;
            end
        end
    endtask

    // ── Main test loop ────────────────────────────────────────────────────────
    integer num_tests, t, msg_len, out_len;
    integer ptr, i, j, bad, pass_cnt, fail_cnt;

    initial begin
        $readmemh("shake256_vectors.hex", vmem);

        // Reset sequence
        rst_n = 0;
        repeat(4) @(posedge clk);
        @(negedge clk); rst_n = 1;
        @(posedge clk);

        // Parse header
        num_tests = {vmem[0], vmem[1], vmem[2], vmem[3]};
        ptr       = 4;
        pass_cnt  = 0;
        fail_cnt  = 0;

        $display("\n=== SHAKE256 KAT: %0d tests ===", num_tests);

        for (t = 0; t < num_tests; t = t + 1) begin
            msg_len = {vmem[ptr],vmem[ptr+1],vmem[ptr+2],vmem[ptr+3]}; ptr += 4;
            out_len = {vmem[ptr],vmem[ptr+1],vmem[ptr+2],vmem[ptr+3]}; ptr += 4;

            for (i = 0; i < msg_len; i++) msg_buf[i] = vmem[ptr + i];
            ptr += msg_len;
            for (i = 0; i < out_len; i++) exp_buf[i] = vmem[ptr + i];
            ptr += out_len;

            // Pulse init, then absorb, then squeeze
            @(negedge clk); init = 1;
            @(posedge clk);
            @(negedge clk); init = 0;

            do_absorb(msg_len);
            do_squeeze(out_len);

            // Byte-by-byte comparison
            bad = 0;
            for (j = 0; j < out_len; j++) if (got_buf[j] !== exp_buf[j]) bad++;

            if (bad == 0) begin
                $display("[PASS] test %0d  msg=%0dB  out=%0dB  %02x%02x%02x%02x...",
                    t, msg_len, out_len,
                    got_buf[0], got_buf[1], got_buf[2], got_buf[3]);
                pass_cnt++;
            end else begin
                $display("[FAIL] test %0d  msg=%0dB  out=%0dB  (%0d bytes wrong)",
                    t, msg_len, out_len, bad);
                $display("  expected %02x%02x%02x%02x...",
                    exp_buf[0], exp_buf[1], exp_buf[2], exp_buf[3]);
                $display("  got      %02x%02x%02x%02x...",
                    got_buf[0], got_buf[1], got_buf[2], got_buf[3]);
                fail_cnt++;
            end
        end

        $display("\n=== %0d / %0d passed ===", pass_cnt, pass_cnt + fail_cnt);
        if (fail_cnt == 0) $display("ALL TESTS PASSED");
        else               $display("FAILURES: %0d", fail_cnt);
        $finish;
    end

endmodule
